name: paypulse_full
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask=2.3.3
  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - requests=2.31.0
  - sqlalchemy=2.0.21
  - openpyxl=3.1.2
  - beautifulsoup4=4.12.2
  - cryptography=41.0.4
  - pillow=10.0.0
  - scipy=1.11.2
  - pip
  - pip:
    - flask-cors==4.0.0
    - chardet==5.2.0
    - python-dateutil==2.8.2
    - werkzeug==2.3.7
    - tensorflow==2.13.0
    - keras==2.13.1
    - plotly==5.15.0
    - selenium==4.12.0
    - python-docx==0.8.11
    - PyPDF2==3.0.1
    - pytz==2023.3
    - bcrypt==4.0.1
    - python-dotenv==1.0.0
    - click==8.1.7
    - pytest==7.4.2
    - pytest-flask==1.2.0
    - loguru==0.7.0
    - redis==4.6.0
    - celery==5.3.1
    - statsmodels==0.14.0