name: paypulse_essential
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask=2.3.3
  - pandas=2.0.3
  - numpy=1.24.3
  - requests=2.31.0
  - pip
  - pip:
    - flask-cors==4.0.0
    - chardet==5.2.0
    - python-dateutil==2.8.2
    - werkzeug==2.3.7